### ISSUE TITLE
Account Epic

### ISSUE THREAD

**Issue by FranckErnewein** [FranckErnewein/tft#7]
- [ ] manage multi topic infra
  - [ ] adapter in memory
  - [ ] adapter for redis
  - [ ] adapter connector for pulsar
